import { Navigation } from "@/Components/Navigation/Navigation";
import "./global.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="body">
        <Navigation />
        {children}
      </body>
    </html>
  );
}
